[package]
authors = ["David Flemström <david.flemstrom@gmail.com>"]
build = "build.rs"
name = "record-query"
version = "0.1.0"

[build-dependencies]

[build-dependencies.lalrpop]
branch = "cargo-out-dir"
git = "https://github.com/dflemstr/lalrpop.git"
path = "lalrpop"

[dependencies]
ansi_term = "0.7.2"
clap = "2.1.1"
env_logger = "0.3.2"
glob = "0.2.10"
log = "0.3.5"
mod_path = "0.1.6"
nix = "0.5.0"
protobuf = "1.0.18"
serde = "0.6.13"
serde_json = "0.6.0"
xdg-basedir = "1.0.0"

[dependencies.lalrpop-util]
branch = "cargo-out-dir"
git = "https://github.com/dflemstr/lalrpop.git"
path = "lalrpop-util"

[profile.release]
lto = true
