[package]
authors = ["David Flemström <david.flemstrom@gmail.com>"]
build = "build.rs"
license = "Apache-2.0"
name = "record-query"
version = "0.9.0"

[build-dependencies]
env_logger = "*"
regex = "*"

[dependencies]
ansi_term = "*"
docopt = "*"
dtoa = "*"
env_logger = "*"
error-chain = "*"
glob = "*"
itoa = "*"
log = "*"
nix = "*"
ordered-float = "*"
pest = "*"
protobuf = "*"
rmp = "*"
rustc-serialize = "*"
serde = "*"
serde-hjson = "*"
serde_cbor = "*"
serde_yaml = "*"
xdg-basedir = "*"
yaml-rust = "*"

[dependencies.serde-avro]
path = "serde-avro"
version = "*"

[dependencies.serde-protobuf]
path = "serde-protobuf"
version = "*"

[dependencies.serde_json]
branch = "v0.9.0"
git = "https://github.com/serde-rs/json.git"

[dependencies.toml]
features = ["serde"]
version = "*"

[dependencies.v8]
git = "https://github.com/dflemstr/v8-rs.git"

[features]
shared = ["v8/shared"]

[profile]

[profile.release]
lto = true
