[package]
authors = ["David Flemström <david.flemstrom@gmail.com>"]
build = "build.rs"
license = "Apache-2.0"
name = "record-query"
version = "0.1.0"

[build-dependencies]
env_logger = "0.3.2"
regex = "0.1.73"

[dependencies]
ansi_term = "0.7.2"
docopt = "0.6.80"
docopt_macros = "0.6.84"
env_logger = "0.3.3"
error-chain = "0.2.1"
glob = "0.2.11"
log = "0.3.6"
nix = "0.5.0"
ordered-float = "0.2.1"
pest = "0.3.2"
protobuf = "1.0.18"
rmp = "0.7.5"
rustc-serialize = "0.3.19"
serde = "0.7.0"
serde-hjson = "0.1.0"
serde_cbor = "0.3.3"
serde_json = "0.7.0"
xdg-basedir = "1.0.0"

[dependencies.duk]
features = ["debug", "logging"]
git = "https://github.com/dflemstr/duk.git"

[dependencies.serde_protobuf]
path = "serde_protobuf"

[profile]

[profile.release]
lto = true
