[package]
authors = ["David Flemström <david.flemstrom@gmail.com>"]
build = "build.rs"
license = "Apache-2.0"
name = "record-query"
version = "0.1.0"

[build-dependencies]
env_logger = "*"
regex = "*"

[dependencies]
ansi_term = "*"
docopt = "*"
env_logger = "*"
error-chain = "*"
glob = "*"
log = "*"
nix = "*"
ordered-float = "*"
pest = "*"
protobuf = "*"
rmp = "*"
rustc-serialize = "*"
serde = "*"
serde-hjson = "*"
serde_cbor = "*"
serde_json = "*"
serde_yaml = "*"
xdg-basedir = "*"
yaml-rust = "*"

[dependencies.duk]
features = ["debug", "logging"]
git = "https://github.com/dflemstr/duk.git"

[dependencies.serde_protobuf]
path = "serde_protobuf"

[profile]

[profile.release]
lto = true
