[package]
authors = ["David Flemström <david.flemstrom@gmail.com>"]
license = "Apache-2.0"
build = "build.rs"
name = "record-query"
version = "0.1.0"

[build-dependencies]
env_logger = "0.3.2"

[build-dependencies.lalrpop]
git = "https://github.com/nikomatsakis/lalrpop.git"
path = "lalrpop"

[dependencies]
ansi_term = "0.7.2"
docopt = "0.6.80"
docopt_macros = "0.6.84"
env_logger = "0.3.3"
glob = "0.2.11"
log = "0.3.6"
mod_path = "0.1.6"
nix = "0.5.0"
ordered-float = "0.2.1"
protobuf = "1.0.18"
rustc-serialize = "0.3.19"
serde = "0.7.0"
serde_cbor = "0.3.3"
serde_json = "0.7.0"
xdg-basedir = "1.0.0"

[dependencies.lalrpop-util]
git = "https://github.com/nikomatsakis/lalrpop.git"
path = "lalrpop-util"

[dependencies.serde_protobuf]
path = "serde_protobuf"

[profile]

[profile.release]
lto = true
